# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

[cmake]
disabled = true

# Change the default prompt format
# ---
# old config ...
# format = """\
# [╭╴](238)$env_var \
# $all[╰─](238)$character"""

# new config
# format = """$env_var $all"""

# Change the default prompt characters
[character]
# old config
# success_symbol = "[](238)"
# error_symbol = "[](238)"
success_symbol = ""
error_symbol = ""

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](white)'
variable = "STARSHIP_DISTRO"
disabled = true

# Shows the username
[username]
style_user = "white"
style_root = "white"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname](bold yellow) "
disabled = false

[directory]
truncation_length = 1
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "via [$symbol$branch]($style) "
# truncation_length = 4
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "󰆼 "
modified = " "
staged = '[++\($count\)](green)'
renamed = " "
deleted = " "

[kubernetes]
format = 'via [ﴱ $context\($namespace\)](bold purple) '
disabled = false

# (deactivated because of no space left)
# 
[terraform]
format = "via [ terraform $version]($style)   [$workspace]($style) "
disabled = true

[vagrant]
format = "via [ vagrant $version]($style) "
disabled = true

[docker_context]
format = "via [ $context](bold blue) "
disabled = true

[helm]
format = "via [ $version](bold purple) "
disabled = true

[python]
python_binary = "python3"
disabled = false
symbol = "🐍 "
format = 'via [$symbol\($virtualenv\) ]($style)'
style  = "fg:color_fg0 bg:color_blue"

[nodejs]
format = "via [ $version](bold green) "
disabled = true

[ruby]
format = "via [ $version]($style) "
disabled = true


"$schema" = 'https://starship.rs/config-schema.json'

# Use the Gruvbox color palette
palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'


format = """
[](color_orange)$os$username
[](bg:color_yellow fg:color_orange)$directory
[](fg:color_yellow bg:color_aqua)$git_branch$git_status
[](fg:color_aqua bg:color_blue)$c$rust$golang$nodejs$php$java$kotlin$haskell$python
[](fg:color_blue bg:color_bg3)$docker_context$conda
[](fg:color_bg3 bg:color_bg1)$time
[ ](fg:color_bg1)
$line_break$character
"""

# # Define the prompt format
# format = """
# [](color_orange)
# $os
# $username
# [](bg:color_yellow fg:color_orange)
# $directory
# [](fg:color_yellow bg:color_aqua)
# $git_branch
# $git_status
# [](fg:color_aqua bg:color_blue)
# $c
# $rust
# $golang
# $nodejs
# $php
# $java
# $kotlin
# $haskell
# $python
# [](fg:color_blue bg:color_bg3)
# $docker_context
# $conda
# [](fg:color_bg3 bg:color_bg1)
# $time
# [ ](fg:color_bg1)
# $line_break$character
# """
