cursor #e5e2e3
cursor_text_color #c6c6cc

foreground            #e5e2e3
background            #131314
selection_foreground  #2e3037
selection_background  #c5c6cf
url_color             #c0c6da

color0   #131314
color1   #fa7095
color2   #6dda7e
color3   #fff872
color4   #b1b8cf
color5   #4e5364
color6   #c0c6da
color7   #d7dae4
color8   #83858d
color9   #ff9fb8
color10  #a5ffb3
color11  #fffba5
color12  #d7ddef
color13  #e9eeff
color14  #f1f4ff
color15  #f8faff
