return {}
-- disable
-- return {
--   config = {
--     settings = {
--       Lua = {
--         diagnostics = {
--           globals = { "getenv", "fv_script" },
--         },
--       },
--     },
--   },
-- }
