local wezterm = require("wezterm")

local M = {}

-- Wallpaper-synced Material You colors, regenerated by matugen whenever the
-- wallpaper changes (see ~/.config/matugen/templates/wezterm-colors.lua and
-- the [templates.wezterm] entry in ~/.config/matugen/config.toml).
-- Falls back to a static scheme if matugen hasn't generated the file yet.
function M.apply(config)
	local ok, matugen_colors = pcall(require, "colors-matugen")
	if ok then
		config.colors = matugen_colors
	else
		config.color_scheme = "Catppuccin Mocha"
	end
	return config
end

return M
