# Generated by Matugen. Do not edit.
# Sourced by apply-rivalcfg-theme.sh to push a static three-zone gradient
# (top/middle/bottom LED strip) to the Aerox 3 Wireless Gen 2.
Z1_COLOR="{{colors.primary.default.hex_stripped}}"
Z2_COLOR="{{colors.secondary.default.hex_stripped}}"
Z3_COLOR="{{colors.tertiary.default.hex_stripped}}"
