# Generated by Matugen. Do not edit.
# Sourced by apply-voyager-theme.sh to set the ZSA Voyager's base-layer RGB
# color over its Oryx raw HID interface (ORYX_SET_BASE_LAYER_COLOR). Only
# the base layer changes -- other layers keep their own indicator colors.
VOYAGER_COLOR="{{colors.primary.default.hex_stripped}}"
