[keyboard]
bindings = [{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" }]

[general]
import = ["./themes/themes/catppuccin_mocha.toml"]

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }

[window]
{{- if eq .chezmoi.os "windows" }}
decorations = "full"
{{- else }}
decorations = "none"
{{- end }}
padding = { x = 10, y = 10 }
opacity = 0.9
